### ISSUE TITLE
(BUG) softlock when dead

### ISSUE THREAD

**Issue by TheComicRelief** [pseudopulse/Moonswept#2]
this error spams and prevents you from opening the menu and respawning when you died

[01:50:40.0137507] [Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Transform.get_position () (at <e27997765c1848b09d8073e5d642717a>:IL_0000)
Moonswept.TZPFogZone.FixedUpdate () (at <9b37d2471eb54f14971749191d39ab22>:IL_0018)

[01:50:40.0137507] [Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Transform.get_position () (at <e27997765c1848b09d8073e5d642717a>:IL_0000)
Moonswept.TZPFogZone.FixedUpdate () (at <9b37d2471eb54f14971749191d39ab22>:IL_0018)

[01:50:40.0467305] [Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Transform.get_position () (at <e27997765c1848b09d8073e5d642717a>:IL_0000)
Moonswept.TZPFogZone.FixedUpdate () (at <9b37d2471eb54f14971749191d39ab22>:IL_0018)

[01:50:40.0467305] [Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Transform.get_position () (at <e27997765c1848b09d8073e5d642717a>:IL_0000)
Moonswept.TZPFogZone.FixedUpdate () (at <9b37d2471eb54f14971749191d39ab22>:IL_0018)

[01:50:40.0480835] [Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Transform.get_position () (at <e27997765c1848b09d8073e5d642717a>:IL_0000)
Moonswept.TZPFogZone.FixedUpdate () (at <9b37d2471eb54f14971749191d39ab22>:IL_0018)

**Comment by Smxrez** [comment]
Unable to reproduce but the latest update now has a failsafe to hopefully prevent this
